### ISSUE TITLE
Finish the task

### ISSUE THREAD

**Issue by HalfSealHalfCat** [mardanovaAA/Laborat#3]
Please complete your [rabbit](https://github.com/mardanovaAA/Laborat/blob/master/Lab5/5.0Clear_code_rabbit.py) and check spacing consistency.

In the second [part](https://github.com/mardanovaAA/Laborat/blob/master/Lab5/5.1Clear_code_Maxim.py) provide consistent docstrings in the way you have done for your [rabbit](https://github.com/mardanovaAA/Laborat/blob/master/Lab5/5.0Clear_code_rabbit.py).

**Comment by mardanovaAA** [comment]
I hope I've fixed it.

**Comment by HalfSealHalfCat** [comment]
> I hope I've fixed it.

Please provide consistent docstrings through all your tasks!
